# This file was generated by GoReleaser. DO NOT EDIT.
class Gpup < Formula
  desc "Upload files to your Google Photos with the new Photos Library API"
  homepage "https://github.com/int128/gpup"
  url "https://github.com/int128/gpup/releases/download/1.6.1/gpup_1.6.1_darwin_amd64.tar.gz"
  version "1.6.1"
  sha256 "f162cf499f12da771caff59c1af6f11def61ffcf2b7b0c5ad3c5423e4124fab4"

  def install
    bin.install "gpup"
  end

  test do
    system "#{bin}/gpup --help"
  end
end
